language: python

python:

  - "2.7.12"
  - "2.7"

install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install flask

script: pytest

after_success: coveralls

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"