language: python

python:

  - "2.7"

  - "3.4"

  - "3.6.1"

install: 
  - pip install -r requirements.txt
  - pip install .

script: pytest --with-coverage --cover-package=tests && coverage report

after_success: coveralls