FORMAT: 1A
HOST: https://stackoverflowlitev3.herokuapp.com/

# Stackoverflow Lite

StackOverflow-lite is a platform where people can ask questions and provide answers. 

##USERS

##Register User [/api/v2/auth/registration]

### Create User [POST]

+ Request 200 (application/json)

        [
           {
                "username":"vashit",
                "email":"vashit@gmail.com",
                "password":"pass1234",
                "confirmpass":"pass1234"
            }     
        ]
        
+ Response 200 (application/json)

        [
            "message": "Successful",
            "user": {
                "email": "vashit@gmail.com",
                "id": 6,
                "username": "vashit"
                    }      
        ]


## QUESTIONS [/api/v2/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "username":"vashit",
                "email":"vashit@gmail.com",
                "password":"pass1234",
                "confirmpass":"pass1234"
            }       
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "body": "Which is the tallest building in Kenya?",
            "created_by": "susan",
            "id": 1,
            "title": "Tallest Buildings",
            "user_id": 1
        }

+ Response 201 (application/json)

    + Headers



    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }